version: '3.7'
services:
  softuni_kubernetes_mysql_db_service:
    container_name: softuni_kubernetes_mysql_db
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - softuni_kubernetes-network
    volumes:
      - softuni_kubernetes_mysqldata:/var/lib/mysql
    environment:
      TZ: Europe/Sofia
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: yourStrongPassword12!@
      MYSQL_DATABASE: softuni_kubernetes_app

  softuni_kubernetes_php_apache2_service:
    container_name: softuni_kubernetes_php_apache2
    build:
      context: ./Server
      dockerfile: ./CarRentalSystemAPI/Dockerfile
    working_dir: /var/www/html
    ports:
      - '5080:80'
      - '5081:443'
    environment:
      CLIENT_URL: http://localhost:5084
      ADMIN_URL: http://localhost:5088
      DB_CONNECTION: mysql
      DB_HOST: softuni_kubernetes_mysql_db
      DB_PORT: 3306
      DB_DATABASE: softuni_kubernetes_app
      DB_USERNAME: root
      DB_PASSWORD: yourStrongPassword12!@
    networks:
      - softuni_kubernetes-network
    depends_on:
      - softuni_kubernetes_mysql_db_service


  softuni_kubernetes_httpd_client_service:
    container_name: softuni_kubernetes_httpd_client
    build:
      context: ./Client
      dockerfile: ./CarRentalSystemClient/Dockerfile
    working_dir: /var/www/html
    ports:
      - '5084:80'
      - '5085:443'
    environment:
      API_URL: http://localhost:5080
    networks:
      - softuni_kubernetes-network
    depends_on:
      - softuni_kubernetes_php_apache2_service
      
  softuni_kubernetes_httpd_admin_service:
    container_name: softuni_kubernetes_httpd_admin
    build:
      context: ./Client
      dockerfile: ./CarRentalSystemAdmin/Dockerfile
    working_dir: /var/www/html
    ports:
      - '5088:80'
      - '5089:443'
    environment:
      API_URL: http://localhost:5080
    networks:
      - softuni_kubernetes-network
    depends_on:
      - softuni_kubernetes_php_apache2_service
volumes:
  softuni_kubernetes_mysqldata:
networks:
  softuni_kubernetes-network:
