version: '3.8'

################################################################################
# SERVICES
################################################################################
services:

################################################################################
# VOLUMES
################################################################################
volumes:

################################################################################
# NETWORK
################################################################################
networks:
