apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: softuni-kubernetes-mysqldata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: softuni-kubernetes-mysql-db
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    database: mysqldb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: softuni-kubernetes-mysql-db
spec:
  serviceName: softuni-kubernetes-mysql-db
  selector:
    matchLabels:
      database: mysqldb
  template:
    metadata:
      labels:
        database: mysqldb
        system: database
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 10001
      containers:
        - name: softuni-kubernetes-mysql-db
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: mysql-tz
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: mysql-allow-empty-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: mysql-database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: mysql-root-password
          volumeMounts:
            - name: softuni-kubernetes-mysqldata
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        - name: softuni-kubernetes-mysqldata
          persistentVolumeClaim:
            claimName: softuni-kubernetes-mysqldata