#Before use need instal: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.7/components.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-admin-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-service
  minReplicas: 1
  maxReplicas: 3 #we have only 300$ free ;-)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  selector:
    matchLabels:
      web-service: admin
  template:
    metadata:
      labels:
        web-service: admin
        system: admin
    spec:
      containers:
        - name: admin-service
          image: 3176a6a/demo-carrentalsystem-admin:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '512Mi'
              cpu: '250m'
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: api-url
