apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  api-url: http://localhost:5080
  admin-url: http://localhost:5088
  client-url: http://localhost:5084
  mysql-tz: Europe/Sofia
  mysql-allow-empty-password: "no"
  api-db-connection: mysql
  api-db-port: "3306"

---

apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  mysql-database: c29mdHVuaV9rdWJlcm5ldGVzX2FwcAo=
  mysql-root-password: eW91clN0cm9uZ1Bhc3N3b3JkMTIhQAo=
  api-db-host: c29mdHVuaV9rdWJlcm5ldGVzX215c3FsX2RiCg==
  api-db-name: c29mdHVuaV9rdWJlcm5ldGVzX2FwcAo=
  api-db-user: cm9vdAo=
  api-db-pass: eW91clN0cm9uZ1Bhc3N3b3JkMTIhQAo=
