apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  api-url: http://localhost:5080
  admin-url: http://localhost:5088
  client-url: http://localhost:5084
  mysql-tz: Europe/Sofia
  mysql-allow-empty-password: "no"
  api-db-connection: mysql
  api-db-port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  mysql-database: c29mdHVuaWt1YmVybmV0ZXM=
  mysql-root-password: eW91clN0cm9uZ1Bhc3N3b3JkMTIhQA==
  api-db-host: c29mdHVuaS1rdWJlcm5ldGVzLW15c3FsLWRi
  api-db-name: c29mdHVuaWt1YmVybmV0ZXM=
  api-db-user: cm9vdA==
  api-db-pass: eW91clN0cm9uZ1Bhc3N3b3JkMTIhQA==
