apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  ports:
    - port: 5080
      targetPort: 80
  selector:
    web-service: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  selector:
    matchLabels:
      web-service: api
  template:
    metadata:
      labels:
        web-service: api
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  web-service: api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: api-service
          image: 3176a6a/demo-carrentalsystem-server:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '512Mi'
              cpu: '250m'
          env:
            - name: CLIENT_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: client-allowed-origins
            - name: ADMIN_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: admin-allowed-origins
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: api-db-connection
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: api-db-port
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: api-db-host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: api-db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: api-db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: api-db-pass
